name: ci

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login do docker.io
        run: docker login -u ${USERNAME} -p ${PASSWORD}
      - name: build and publish image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./3.10.1
          file: ./3.10.1/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          tags: |
            ${USERNAME}/iperf-server-v3.10.1:latest
